ARG NGX_VERSION=1.28.3
# NGINX official images are available for one specific release of Debian,
# e.g `nginx:1.28.3-trixie`. Please see the list of tags on Docker Hub
# if you need to change NGX_VERSION.
ARG DEBIAN_RELEASE=trixie

FROM docker.io/library/rust:slim-${DEBIAN_RELEASE} AS build

ARG NGX_VERSION

WORKDIR /warm

RUN --mount=type=cache,target=/var/cache/apt \ 
    --mount=type=cache,target=/var/lib/apt \ 
    apt update && \
    apt install -y --no-install-recommends --no-install-suggests \
    libpcre2-dev libssl-dev zlib1g-dev make git libclang-dev pkg-config libmodsecurity3 libmodsecurity-dev

COPY rust/src src
COPY rust/Cargo.toml Cargo.toml

RUN --mount=type=cache,id=cargo,target=/usr/local/cargo/registry \
    cargo fetch

RUN --mount=type=cache,id=cache,target=.cache \
    --mount=type=cache,id=cargo,target=/usr/local/cargo/registry \
    cargo build --release

COPY container/warm.conf .

FROM docker.io/library/nginx:${NGX_VERSION}-${DEBIAN_RELEASE}

COPY --from=build /warm/target/release/libwarm.so /etc/nginx/modules/libwarm.so
COPY --from=build /warm/warm.conf /etc/nginx/conf.d/warm.conf

RUN --mount=type=cache,target=/var/cache/apt \ 
    --mount=type=cache,target=/var/lib/apt \
    apt update && apt install -y libmodsecurity3

EXPOSE 8000

CMD ["nginx", "-c", "/etc/nginx/conf.d/warm.conf"]
