daemon off;
master_process off;
# worker_processes  1;

# on linux load a module:
load_module modules/libwarm.so;

# error_log /dev/stdout debug;
error_log error.log debug;

events { }

http {
    server {
        listen *:8000;
        server_name localhost;
        location / {
            root   html;
            index  index.html index.htm;
            # libcurl module directive:
            warm on;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}