[package]
name = "warm-ml"
version = "0.1.0"
edition = "2024"

[[example]]
name = "train"
crate-type = ["bin"]

[[example]]
name = "test"
crate-type = ["bin"]

[dependencies]
bincode = {version="2", features=["serde"]}
csv = "1.4.0"
http = "1.4.0"
linfa = { version="0.8.1", features = ["serde"] }
linfa-logistic = {version="0.8.1", features = ["serde"]}
linfa-svm = {version="0.8.1",features = ["serde"]}
modsecurity = {workspace = true}
ndarray = "0.16.1"
rand = "0.10.1"
regex = "1.12.3"
serde = "1.0.228"
serde_json = "1.0.149"
urlencoding = "2.1.3"